FROM nginx:1.27-alpine
RUN apk add --no-cache apache2-utils
COPY cfg-entry.sh /cfg-entry.sh
RUN chmod 755 /cfg-entry.sh \
 && rm -f /etc/nginx/conf.d/default.conf \
 && mkdir -p /srv/private/core /etc/nginx/htpasswd
COPY nginx.conf /etc/nginx/conf.d/private.conf
ENTRYPOINT ["/cfg-entry.sh"]
