server {
    listen 80;
    location /core/ {
        alias /srv/private/core/;
        auth_basic "cfg";
        auth_basic_user_file /etc/nginx/htpasswd/htpasswd;
        autoindex on;
    }
    location / {
        return 404 "cfg\n";
    }
}
